version: '3.9'

x-base_service: &base_service
    ports:
      - "${WEBUI_PORT:-7860}:7860"
    volumes:
      - &v1 ./data:/data
      - &v2 ./output:/output
      - &v3 ./output/fooocus:/Fooocus/outputs
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]

name: webui-docker

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - *v1

  aigcion: &aigcion
      <<: *base_service
      ports:
      - "${WEBUI_PORT:-5000}:5000"
      profiles: ["aigcion"]
      build: ./services/aigcion
      image: aigcion:01

  auto: &automatic
    <<: *base_service
    ports:
      - "7860:7860"
    profiles: ["auto"]
    build: ./services/AUTOMATIC1111
    image: sd-auto:67
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api

  fooocus: &fooocus
    <<: *base_service
    volumes:
      - *v1
      - *v3
    ports:
      - "7861:7860"
    stdin_open: true
    tty: true
    container_name: fooocus
    profiles: ["fooocus"]
    build: ./services/fooocus
    image: sd-fooocus:1
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api

  comfy: &comfy
    <<: *base_service
    ports:
      - "${WEBUI_PORT:-7862}:7860"
    profiles: ["comfy"]
    build: ./services/comfy/
    image: sd-comfy:5
    environment:
      - CLI_ARGS=

  # auto-cpu:
  #   <<: *automatic
  #   profiles: ["auto-cpu"]
  #   deploy: {}
  #   environment:
  #     - CLI_ARGS=--no-half --precision full --allow-code --enable-insecure-extension-access --api

  # invoke: &invoke
  #   <<: *base_service
  #   profiles: ["invoke"]
  #   build: ./services/invoke/
  #   image: sd-invoke:30
  #   environment:
  #     - PRELOAD=true
  #     - CLI_ARGS=--xformers

  # invoke-cpu:
  #   <<: *invoke
  #   profiles: ["invoke-cpu"]
  #   environment:
  #     - PRELOAD=true
  #     - CLI_ARGS=--always_use_cpu

  # comfy-cpu:
  #   <<: *comfy
  #   profiles: ["comfy-cpu"]
  #   deploy: {}
  #   environment:
  #     - CLI_ARGS=--cpu
